### ISSUE TITLE
Unexpected Token in Json

### ISSUE THREAD

**Issue by markush97** [Jodebu/upload-to-drive#6]
```
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/runner/work/_actions/Jodebu/upload-to-drive/master/dist/index.js:1:412513)
    at __webpack_require__ (/home/runner/work/_actions/Jodebu/upload-to-drive/master/dist/index.js:1:169)
``` 
I am getting this error, even tho I am using a Base64 encoded json in the same format as you are

**Comment by mathisve** [comment]
Same issue here.
I tried running the json decoding code in question:
```js
const credentials = "base64 encoded json";
const credentialsJSON = JSON.parse(Buffer.from(credentials, 'base64').toString());
console.log(credentialsJSON);
```

And it works perfectly fine.
So it must not be that? Despite that erroring out, and that also being the only occurrence of `JSON.parse`.
Strange ...

**Comment by mathisve** [comment]
I'm not really for advertising on Github. But since it doesn't look like this will get fixed, we made our own Github Actions Google Drive upload module. Written in Golang.
Works largely in the same way.
https://github.com/team-tumbleweed/gdrive-upload-action

**Comment by ghost** [comment]
The README is misleading here. The first example shows `credentials: secrets.<YOUR_DRIVE_CREDENTIALS>` when it should actually be `credentials: ${{ secrets.<YOUR_DRIVE_CREDENTIALS> }}`. If you have not wrapped "secrets..." in ${{ }} then the Action will Base64 decode "secrets..." and then attempt to JSON parse that.

**Comment by mohammedismayil** [comment]
They have probably missed that because we usually give the repository secrets in ${{ secrets.OURKEYS }} format.
